# Setup
title:               "Starrysky의 수학 노트"
tagline:             "Younghun Jo's Homepage"
name:              "Younghun Jo"
author:           "Starrysky"
department: "Department of Mathematical Sciences, Seoul National University"
description:         "A personal website about random mathematical things I study."
url:                 https://Starrysky422.github.io
baseurl:             ""
paginate:            5
paginate_path: "page:num" 
permalink:           pretty

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y


