# Setup
title:               "Starrysky의 수학 노트"
tagline:             "Younghun Jo's Homepage"
name:                "Younghun Jo"
department:          "Department of Mathematical Sciences, Seoul National University"
description:         "A personal website about random mathematical stuffs I study."
url:                 https://Starrysky422.github.io
baseurl:             ""
paginate:            5
paginate_path:       "page:num" 
permalink:           pretty

# Author Setup
author:
  name: "Starrysky"
  email: "starrysky422@snu.ac.kr"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed

# Custom vars
version:             1.1.0
google_analytics_id: "G-R5HWL64QX2"


