# Setup
title:               "Starrysky의 수학 노트"
tagline:             "Younghun Jo's Homepage"
description:         "A personal website about random mathematical things I study."
url:                 https://Starrysky422.github.io
baseurl:             ""
paginate:            5
permalink:           pretty

# About/contact
author:
  name:              Younghun Jo
  url:               https://www.facebook.com/younghunj
  email:             starrysky422@snu.ac.kr

# Gems
plugins:
  - jekyll-paginate

# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
