# Setup
title:               "Mathematical Scribbles"
tagline:             "Younghun Jo's Homepage"
name:                "Younghun Jo"
department:          "Department of Mathematics, MIT"
description:         "A personal website about random mathematical stuff I study."
url:                 https://Starrysky422.github.io
baseurl:             ""
paginate:            5
paginate_path:       "page:num" 
permalink:           pretty
timezone:            America/New_York

# Author Setup
author:
  name: "Starrysky"
  email: "yhun_jo@mit.edu"

# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false

# Gems
plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-email-protect

# Custom vars
version:             1.1.0
google_analytics_id: "G-R5HWL64QX2"


